INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STUDENT', '2018-09-14 02:00:00', 'John', 'Banderman', 'Ghana', 1);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STAFF', '2018-09-14 02:00:00', 'Marc', 'De Grijs', 'Belgium', 2);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STUDENT', '2018-09-09 02:00:00', 'Ntambwe', 'Molowayi', 'DRC', 3);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STAFF', '2018-09-23 02:00:00', 'Jack', 'Abbot', 'USA', 4);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STAFF', '2018-09-22 02:00:00', 'Henri', 'Kissisnger', 'USA', 5);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STUDENT', '2018-09-12 02:00:00', 'Lou', 'Ferinho', 'USA', 6);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STUDENT', '2018-09-21 02:00:00', 'Sean', 'Pen', 'USA', 7);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STUDENT', '2018-09-20 02:00:00', 'Timo', 'VERMEULEN', 'Belgium', 8);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STUDENT', '2018-04-13 02:00:00', 't-Ntambwe', 'ttttttttttt', 'DRC', 9);
INSERT INTO db_eindwerk.person (status, birth_date, first_name, last_name, origin, contact) VALUES ('STAFF', '2018-06-13 02:00:00', 'Johnny', 'Haliday', 'France', 10);